# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00cee161ce32470c13a65d9ae62fe132a8e51827ed0a57557eecc1425d9e9e0ea7dc281c4aa1d05057f34f1db835d684fdd8cd33e99d21103f02a5d40f95f220

test:
  secret_key_base: 08b5b87fe450d5802a2726703caca4e4cb0cdb25953887ede4e51360b3f039a1d4b54a7214633ea8a317f6bd490a3189a44f7c4d21d82e7402e215170c597d55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
